// Generated by CoffeeScript 1.10.0
var Animal, Cat, Dog, Horse, animals, atLeastMe, cat, cat2, dog, j, k, l, len, len1, len2, other, pet,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Animal = (function() {
  function Animal(petType, petName1, x1) {
    this.petType = petType;
    this.petName = petName1;
    this.x = x1;
    this.sleep = false;
    this.dx = 1;
    this.health = 10;
    return;
  }

  Animal.prototype.walk = function() {
    this.x += this.dx;
    if (this.x === 0 || this.x === 11) {
      this.dx = -this.dx;
      return this.health--;
    }
  };

  Animal.prototype.isTired = function() {
    return this.health === 0;
  };

  Animal.prototype.collide = function(animal) {
    return animal.x === this.x && !animal.sleep && !this.sleep;
  };

  Animal.prototype.show = function() {
    return console.log(this.petType + " " + this.petName + " is at " + this.x);
  };

  Animal.prototype.rest = function() {
    if (!this.sleep) {
      console.log(this.petType + " " + this.petName + " takes a break at " + this.x);
    }
    return this.sleep = true;
  };

  Animal.prototype.greeting = function(other) {
    return console.log(this.petType + " " + this.petName + ": 'Hello " + other.petType + " " + other.petName + ". We are in " + this.x + ".'");
  };

  return Animal;

})();

Cat = (function(superClass) {
  extend(Cat, superClass);

  function Cat(petName, x) {
    Cat.__super__.constructor.call(this, "Cat", petName, x);
    return;
  }

  Cat.prototype.walk = function() {
    console.log("> walk <");
    return Cat.__super__.walk.call(this);
  };

  return Cat;

})(Animal);

Dog = (function(superClass) {
  extend(Dog, superClass);

  function Dog(petName, x) {
    Dog.__super__.constructor.call(this, "Dog", petName, x);
    return;
  }

  Dog.prototype.run = function() {
    var i, j, results;
    results = [];
    for (i = j = 1; j <= 3; i = ++j) {
      results.push(this.walk());
    }
    return results;
  };

  return Dog;

})(Animal);

Horse = (function(superClass) {
  extend(Horse, superClass);

  function Horse(petName, x) {
    Horse.__super__.constructor.call(this, "Horse", petName, x);
    return;
  }

  Horse.prototype.gallop = function() {
    var i, j, results;
    results = [];
    for (i = j = 1; j <= 6; i = ++j) {
      results.push(this.walk());
    }
    return results;
  };

  return Horse;

})(Animal);

cat = new Cat("mimi", 2);

dog = new Dog("kiki", 0);

cat2 = new Cat("meomeo", 5);

animals = [cat, dog, cat2, new Horse("hehe", 9)];


/*
while !cat.isTired()
    cat.walk()
    cat.show()

allTired =(array) ->
    all = true
    while all && pet for pet in array
        if !pet.isTired()
            all=false
    return all

while !cat.isTired || !dog.isTired()
    cat.walk();
    dog.run()
    cat.show()
    dog.show()

    if cat.collide(dog)
        cat.greeting(dog)
 */

atLeastMe = true;

for (j = 0, len = animals.length; j < len; j++) {
  pet = animals[j];
  pet.show();
}

console.log("-----------------");

while (atLeastMe) {
  atLeastMe = false;
  for (k = 0, len1 = animals.length; k < len1; k++) {
    pet = animals[k];
    if (pet.isTired()) {
      pet.rest();
    } else {
      atLeastMe = true;
      switch (pet.petType) {
        case "Cat":
          pet.walk();
          break;
        case "Dog":
          pet.run();
      }
      pet.show();
      for (l = 0, len2 = animals.length; l < len2; l++) {
        other = animals[l];
        if (other !== pet && pet.collide(other)) {
          pet.greeting(other);
        }
      }
    }
  }
}
