// Generated by CoffeeScript 1.10.0
var BubbleSort;

BubbleSort = (function() {
  function BubbleSort(data) {
    this.data = data;
    this.time = 0;
    this.space = 0;
    return;
  }

  BubbleSort.prototype.doSort = function() {
    var i, j, k, l, n, ref, ref1, starting, tmp;
    this.space = this.data.length;
    starting = window.performance.now();
    n = this.data.length;
    for (i = k = ref = n - 1; k >= 0; i = k += -1) {
      for (j = l = ref1 = n - i; l >= 1; j = l += -1) {
        if (this.data[j] < this.data[j - 1]) {
          tmp = this.data[j];
          this.data[j] = this.data[j - 1];
          this.data[j - 1] = tmp;
        }
      }
    }
    return this.time = window.performance.now() - starting;
  };

  return BubbleSort;

})();
