// Generated by CoffeeScript 1.10.0
var BubbleSort;

BubbleSort = (function() {
  function BubbleSort(data) {
    this.data = data;
    this.time = 0;
    this.space = 0;
    return;
  }

  BubbleSort.prototype.doSort = function() {
    var i, j, k, l, m, n, ref, ref1, starting, t, temp, tmp;
    this.space = this.data.length;
    starting = window.performance.now();
    n = this.data.length;
    for (t = k = 1; k <= 5; t = ++k) {
      temp = this.data.slice();
      for (i = l = ref = n - 1; l >= 0; i = l += -1) {
        for (j = m = ref1 = n - i; m >= 1; j = m += -1) {
          if (temp[j] < temp[j - 1]) {
            tmp = temp[j];
            temp[j] = temp[j - 1];
            temp[j - 1] = tmp;
          }
        }
      }
    }
    this.time = (window.performance.now() - starting) / 5;
    return this.data = temp;
  };

  return BubbleSort;

})();
