// Generated by CoffeeScript 1.10.0
var bubbleSort;

bubbleSort = function(data, n) {
  var i, j, k, l, now, ref, ref1, starting, tmp;
  starting = window.performance.now();
  for (i = k = ref = n - 1; k >= 0; i = k += -1) {
    for (j = l = ref1 = n - i; l >= 1; j = l += -1) {
      if (data[j] < data[j - 1]) {
        tmp = data[j];
        data[j] = data[j - 1];
        data[j - 1] = tmp;
      }
    }
  }
  now = window.performance.now();
  return now - starting;
};
