// Generated by CoffeeScript 1.10.0
var GenerateData;

GenerateData = (function() {
  function GenerateData() {}

  GenerateData.prototype.random = function(n) {
    var i, j, ref, rv;
    rv = [];
    for (i = j = 1, ref = n; 1 <= ref ? j <= ref : j >= ref; i = 1 <= ref ? ++j : --j) {
      rv.push(Math.floor(Math.random() * n));
    }
    return rv;
  };

  GenerateData.prototype.reversed = function(n) {
    var i, j, ref, rv;
    rv = [];
    for (i = j = 1, ref = n; 1 <= ref ? j <= ref : j >= ref; i = 1 <= ref ? ++j : --j) {
      rv.push(n + Math.floor(Math.random() * (n / 10)) - Math.floor(n / 20));
    }
    return rv;
  };

  GenerateData.prototype.sorted = function(n) {
    var i, j, ref, rv;
    rv = [];
    for (i = j = 1, ref = n; 1 <= ref ? j <= ref : j >= ref; i = 1 <= ref ? ++j : --j) {
      rv.push(i + Math.floor(Math.random() * (n / 10)) - Math.floor(n / 20));
    }
    return rv;
  };

  return GenerateData;

})();
