// Generated by CoffeeScript 1.10.0
var generateRandomData, generateReversedData, generateSortedData, insertionSort, show;

generateRandomData = function(n) {
  var i, k, ref, rv;
  rv = [];
  for (i = k = 1, ref = n; 1 <= ref ? k <= ref : k >= ref; i = 1 <= ref ? ++k : --k) {
    rv.push(Math.floor(Math.random() * n));
  }
  return rv;
};

generateReversedData = function(n) {
  var i, k, ref, rv;
  rv = [];
  for (i = k = 1, ref = n; 1 <= ref ? k <= ref : k >= ref; i = 1 <= ref ? ++k : --k) {
    rv.push(n + Math.floor(Math.random() * (n / 10)) - Math.floor(n / 20));
  }
  return rv;
};

generateSortedData = function(n) {
  var i, k, ref, rv;
  rv = [];
  for (i = k = 1, ref = n; 1 <= ref ? k <= ref : k >= ref; i = 1 <= ref ? ++k : --k) {
    rv.push(i + Math.floor(Math.random() * (n / 10)) - Math.floor(n / 20));
  }
  return rv;
};

insertionSort = function(data, n) {
  var i, j, k, now, ref, starting, value;
  starting = window.performance.now();
  for (i = k = 1, ref = n - 1; 1 <= ref ? k <= ref : k >= ref; i = 1 <= ref ? ++k : --k) {
    j = i - 1;
    value = data[i];
    while (j >= 0 && value < data[j]) {
      data[j + 1] = data[j];
      j = j - 1;
    }
    data[j + 1] = value;
  }
  now = window.performance.now();
  return now - starting;
};

show = function(data, time1, time2, n) {
  var i, k, ref, results;
  results = [];
  for (i = k = 0, ref = n - 1; 0 <= ref ? k <= ref : k >= ref; i = 0 <= ref ? ++k : --k) {
    results.push(console.log('@' + time1[i] + ' @' + time2[i](+': ' + data[i])));
  }
  return results;
};
