// Generated by CoffeeScript 1.10.0
var InsertionSort;

InsertionSort = (function() {
  function InsertionSort(data) {
    this.data = data;
    this.time = 0;
    this.space = 0;
    return;
  }

  InsertionSort.prototype.doSort = function() {
    var i, j, k, ref, starting, value;
    this.space = this.data.length;
    starting = window.performance.now();
    for (i = k = 1, ref = this.data.length - 1; 1 <= ref ? k <= ref : k >= ref; i = 1 <= ref ? ++k : --k) {
      j = i - 1;
      value = this.data[i];
      while (j >= 0 && value < this.data[j]) {
        this.data[j + 1] = this.data[j];
        j = j - 1;
      }
      this.data[j + 1] = value;
    }
    return this.time = window.performance.now() - starting;
  };

  return InsertionSort;

})();
