// Generated by CoffeeScript 1.10.0
var MergeSort;

MergeSort = (function() {
  function MergeSort(data1) {
    this.data = data1;
    this.time = 0;
    this.space = 0;
    return;
  }

  MergeSort.prototype.doSort = function() {
    var starting;
    starting = window.performance.now();
    this.data = this.merge(this.data);
    this.time = window.performance.now() - starting;
  };

  MergeSort.prototype.merge = function(data) {
    var left, midpoint, right, rv;
    if (data.length === 1) {
      return data;
    }
    this.space = this.space + data.length;
    rv = [];
    midpoint = Math.floor(data.length / 2);
    left = this.merge(data.slice(0, midpoint));
    right = this.merge(data.slice(midpoint));
    while (left.length && right.length) {
      rv.push(left[0] < right[0] ? left.shift() : right.shift());
    }
    return rv.concat(left).concat(right);
  };

  return MergeSort;

})();
