// Generated by CoffeeScript 1.10.0
var mergeSort;

mergeSort = function(data) {
  var left, midpoint, right, rv;
  if (data.length === 1) {
    return data;
  }
  rv = [];
  midpoint = Math.floor(data.length / 2);
  left = mergeSort(data.slice(0, midpoint));
  right = mergeSort(data.slice(midpoint));
  while (left.length && right.length) {
    rv.push(left[0] < right[0] ? left.shift() : right.shift());
  }
  return rv.concat(left).concat(right);
};
