// Generated by CoffeeScript 1.10.0
var SelectionSort;

SelectionSort = (function() {
  function SelectionSort(data) {
    this.data = data;
    this.time = 0;
    this.space = 0;
    return;
  }

  SelectionSort.prototype.doSort = function() {
    var i, j, k, l, min, n, ref, ref1, ref2, starting, temp;
    this.space = this.data.length;
    starting = window.performance.now();
    n = this.data.length;
    for (i = k = 1, ref = n - 1; 1 <= ref ? k <= ref : k >= ref; i = 1 <= ref ? ++k : --k) {
      min = i;
      for (j = l = ref1 = i + 1, ref2 = n - 1; ref1 <= ref2 ? l <= ref2 : l >= ref2; j = ref1 <= ref2 ? ++l : --l) {
        if (this.data[j] < this.data[min]) {
          min = j;
        }
      }
      if (i !== min) {
        temp = this.data[i];
        this.data[i] = this.data[min];
        this.data[min] = temp;
      }
    }
    return this.time = window.performance.now() - starting;
  };

  return SelectionSort;

})();
