// Generated by CoffeeScript 1.10.0
var selectionSort, swap;

swap = function(data, i, j) {
  var temp;
  temp = data[i];
  data[i] = data[j];
  return data[j] = temp;
};

selectionSort = function(data, n) {
  var i, j, k, l, min, now, ref, ref1, ref2, starting;
  starting = window.performance.now();
  for (i = k = 1, ref = n - 1; 1 <= ref ? k <= ref : k >= ref; i = 1 <= ref ? ++k : --k) {
    min = i;
    for (j = l = ref1 = i + 1, ref2 = n - 1; ref1 <= ref2 ? l <= ref2 : l >= ref2; j = ref1 <= ref2 ? ++l : --l) {
      if (data[j] < data[min]) {
        min = j;
      }
    }
    if (i !== min) {
      swap(data, i, min);
    }
  }
  now = window.performance.now();
  return now - starting;
};
